const express = require("express")
const dotenv = require("dotenv")
const SwaggerConfig = require("./src/config/swagger.config")
const mainRouter = require("./src/app.routes")
const NotFoundHandler = require("./src/common/exception/not-found.handler")
const AllExceptionHandler = require("./src/common/exception/all-exception.handler")
const cookieParser = require("cookie-parser")
const expressEjsLayouts = require("express-ejs-layouts")
const moment = require("jalali-moment")
const methodOverride = require("method-override")
const connectDB = require("./src/config/mongoose.config")
dotenv.config()

async function main() {
    const app = express()
    const port = process.env.PORT || 3000
    await connectDB()
    app.use(express.json())
    app.use(express.urlencoded({ extended: true }))
    app.use(cookieParser(process.env.COOKIE_SECRET_KEY))
    app.use(express.static("public"))
    app.use(expressEjsLayouts)
    app.use(methodOverride('_method'))
    app.set("view engine", "ejs")
    app.set("layout extractScripts", true)
    app.set("layout extractStyles", true)
    app.set("layout", "./layouts/panel/main.ejs")
    app.use(mainRouter)
    app.locals.moment = moment
    SwaggerConfig(app)
    NotFoundHandler(app)
    AllExceptionHandler(app)
    app.listen(port, () => console.log(`سرور روی پورت ${port} در حال اجرا است`))
}
main().catch((err) => {
    console.log(err?.message ?? "راه‌اندازی سرور ناموفق بود")
    process.exit(1)
})
